//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.KensSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.KensSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during compression or decompression..
        /// </summary>
        internal static string CompressionExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("CompressionExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonicRetro.KensSharp.PaddedStream.Flush can only be called on streams in write mode..
        /// </summary>
        internal static string PaddedStreamFlushRequiresWriteMode {
            get {
                return ResourceManager.GetString("PaddedStreamFlushRequiresWriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonicRetro.KensSharp.PaddedStream.Read can only be called on streams in read mode..
        /// </summary>
        internal static string PaddedStreamReadRequiresReadMode {
            get {
                return ResourceManager.GetString("PaddedStreamReadRequiresReadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified offset points to before the start of the stream..
        /// </summary>
        internal static string PaddedStreamSeekToBeforeStartOfStream {
            get {
                return ResourceManager.GetString("PaddedStreamSeekToBeforeStartOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonicRetro.KensSharp.PaddedStream.SetLength can only be called on streams in write mode..
        /// </summary>
        internal static string PaddedStreamSetLengthRequiresWriteMode {
            get {
                return ResourceManager.GetString("PaddedStreamSetLengthRequiresWriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonicRetro.KensSharp.PaddedStream.Write can only be called on streams in write mode..
        /// </summary>
        internal static string PaddedStreamWriteRequiresWriteMode {
            get {
                return ResourceManager.GetString("PaddedStreamWriteRequiresWriteMode", resourceCulture);
            }
        }
    }
}
