//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.KensSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.KensSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit code is already used as a prefix for other codes..
        /// </summary>
        internal static string CodeAlreadyUsedAsPrefix {
            get {
                return ResourceManager.GetString("CodeAlreadyUsedAsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence of bits results in a code that isn&apos;t defined in the code tree..
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;count&apos; is negative..
        /// </summary>
        internal static string NegativeCount {
            get {
                return ResourceManager.GetString("NegativeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;offset&apos; is negative..
        /// </summary>
        internal static string NegativeOffset {
            get {
                return ResourceManager.GetString("NegativeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;offset&apos; is greater than the size of &apos;buffer&apos;..
        /// </summary>
        internal static string OffsetIsGreaterThanBufferSize {
            get {
                return ResourceManager.GetString("OffsetIsGreaterThanBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of &apos;offset&apos; and &apos;count&apos; is greater than the size of &apos;buffer&apos;..
        /// </summary>
        internal static string OffsetPlusCountIsGreaterThanBufferSize {
            get {
                return ResourceManager.GetString("OffsetPlusCountIsGreaterThanBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit code prefix is already used for a complete bit code..
        /// </summary>
        internal static string PrefixAlreadyUsedAsCode {
            get {
                return ResourceManager.GetString("PrefixAlreadyUsedAsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining length of the specified input stream is greater than Int32.MaxValue (0x7fffffff)..
        /// </summary>
        internal static string StreamIsTooLong {
            get {
                return ResourceManager.GetString("StreamIsTooLong", resourceCulture);
            }
        }
    }
}
